CREATE TABLE USUARIO (
	RUN VARCHAR(10) PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(50),
	PRIMER_APELLIDO VARCHAR(50),
	SEGUNDO_APELLIDO VARCHAR(50),
	EMAIL VARCHAR(100),
	FOTO BYTEA
);

CREATE TABLE REGISTRO (
	R_RUN VARCHAR(10),
	FECHA_INGRESO DATE,
	FECHA_SALIDA DATE,
	ACTIVIDAD VARCHAR(2),
	PRIMARY KEY(R_RUN, FECHA_INGRESO),
	FOREIGN KEY(R_RUN) REFERENCES USUARIO
);

CREATE USER ingresoRaspberry WITH PASSWORD 'admin123';
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USUARIO TO ingresoRaspberry;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE REGISTRO TO ingresoRaspberry;